/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pub.frames;

/**
 *
 * @author gerry
 */
public class pgInicio extends javax.swing.JPanel {

    /**
     * Creates new form pgInicio
     */
    public pgInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWelcome1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 31, 37));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWelcome1.setBackground(new java.awt.Color(0, 0, 0));
        txtWelcome1.setFont(new java.awt.Font("SF Pro Text", 1, 48)); // NOI18N
        txtWelcome1.setForeground(new java.awt.Color(188, 183, 174));
        txtWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWelcome1.setText("Welcome !");
        add(txtWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 400, 95));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtWelcome1;
    // End of variables declaration//GEN-END:variables
}
